language: rust
rust:
- stable
- beta
- nightly
script:
- cargo test --verbose --release
os:
- linux
- osx
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true

before_install:
  - echo "ENV:"
  - echo "TRAVIS_OS_NAME=$TRAVIS_OS_NAME"
  - echo "TRAVIS_RUST_VERSION=$TRAVIS_RUST_VERSION"
  - echo "TRAVIS_TAG=$TRAVIS_TAG"
  - if [[ ("$TRAVIS_OS_NAME" == "linux") && ("$TRAVIS_RUST_VERSION" == "stable") && ("$TRAVIS_TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.linux$) ]]; then export LINUX_DEPLOY="true"; fi
  - if [[ ("$TRAVIS_OS_NAME" == "osx") && ("$TRAVIS_RUST_VERSION" == "stable") && ("$TRAVIS_TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.osx$) ]]; then export OSX_DEPLOY="true"; fi
  - echo "$OSX_DEPLOY"
  - echo "$LINUX_DEPLOY"

deploy:
  - provider: releases
    api_key:
      secure: ve4sGZMVasUuME9tvaG0V3fjbJAg+of7ZqsGlLknTQ8svqR4b9NFPZcJoeCZypwiFTOZOvukKW7L+icW/2nm0fpeXoAGq7nEQwsns19Z6VSw+VuRIWsX34vJYz0tOc5uTm+ZfFOBwkiXlXoxaDLh7VYPccmJCb5zaumNESaLOe+ZQ7FbetyZe6+yHsZoapsteveY3hu3wp0jL59vToQvFX1JXlvrzD7uvp7RbfqbqjwY9zqYYIgpzDz5XcaG1yV5ffF+5MXvi9pjnlPwrzn7TRdoslOcxvndmJXwZOgoXRNVu+FZsqVmJpcAjPB/8193gD2bj2Rv4DaMvlM1YdZ7UBv6OnoV3uu2ckBB32k3IzOOi+q47MU4ekN06Oxo2afSs9r9wDW8EFrX8PhFhqjx5DrwAfhBMNk7OyncQ/sV6T7UpoHdv+eeknH/ls8/SgDcrshfAlDZIdAqsYFD06M2zx4EOd9h9mgsgWDmN0ogG8w5PCANusxpDXsz4Ge7awP4SFpwddvzwfChwOqYYVe80RHAP9PGZtt4cB0tL+jWneYFNTXJh2hbBvrXV434Td65315FfWZrdI+bPkD/ike3budUsLgr1AeDMn2T4NWXOf+AIIeFUEjk99wW398qPJzwQJlqtwltkt6k+oIc2oc0MG0+JIjSdD390RFCzOQ3N88=
    file:
      - "./target/release/jg"
    skip_cleanup: true
    on:
      condition: $LINUX_DEPLOY = "true"
      tags: true
      repo: gmmorris/jg
  - provider: releases
    api_key: "GITHUB API KEY"
    api_key:
      secure: ve4sGZMVasUuME9tvaG0V3fjbJAg+of7ZqsGlLknTQ8svqR4b9NFPZcJoeCZypwiFTOZOvukKW7L+icW/2nm0fpeXoAGq7nEQwsns19Z6VSw+VuRIWsX34vJYz0tOc5uTm+ZfFOBwkiXlXoxaDLh7VYPccmJCb5zaumNESaLOe+ZQ7FbetyZe6+yHsZoapsteveY3hu3wp0jL59vToQvFX1JXlvrzD7uvp7RbfqbqjwY9zqYYIgpzDz5XcaG1yV5ffF+5MXvi9pjnlPwrzn7TRdoslOcxvndmJXwZOgoXRNVu+FZsqVmJpcAjPB/8193gD2bj2Rv4DaMvlM1YdZ7UBv6OnoV3uu2ckBB32k3IzOOi+q47MU4ekN06Oxo2afSs9r9wDW8EFrX8PhFhqjx5DrwAfhBMNk7OyncQ/sV6T7UpoHdv+eeknH/ls8/SgDcrshfAlDZIdAqsYFD06M2zx4EOd9h9mgsgWDmN0ogG8w5PCANusxpDXsz4Ge7awP4SFpwddvzwfChwOqYYVe80RHAP9PGZtt4cB0tL+jWneYFNTXJh2hbBvrXV434Td65315FfWZrdI+bPkD/ike3budUsLgr1AeDMn2T4NWXOf+AIIeFUEjk99wW398qPJzwQJlqtwltkt6k+oIc2oc0MG0+JIjSdD390RFCzOQ3N88=
    file:
      - "./target/release/jg"
    skip_cleanup: true
    on:
      condition: $OSX_DEPLOY = "true"
      tags: true
      repo: gmmorris/jg
