language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose --release
  - cargo test --verbose
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true